name: hello-world-2
on:
  - push
  - pull_request
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  my-job2:
    runs-on: ubuntu-latest
    steps:
      - name: my-step-2
        run: echo "Hello World again!"