name: use-secrets-from-repo
on:
  - push
  - pull_request
jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
        HOSTNAME: ${{ secrets.HOSTNAME }}
        USERNAME: ${{ secrets.USERNAME }}
        AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
    steps:
      - name: connect to EC2
        run: |
            echo "If we retrieve the env variables, comming from secrets, we will see *** instead of value, for security porpouses"
            echo ${{ env.HOSTNAME }}
            echo ${{ env.USERNAME }}
            echo "${{ env.AWS_PRIVATE_KEY }}" > private_key && chmod 600 private_key
            ssh -q -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '

                #Now we have got the access of EC2 and we will start the deploy .
                echo "Connected to EC2 instance!"
            '