name: Sync with S3 bucket

on:
  push:
    branches: ['master']
    paths: ['documentation/images/**']

jobs:

  sync:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET : ${{secrets.S3_BUCKET}}

    steps:

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{env.AWS_REGION}}

      - uses: actions/checkout@v2

      - name: Sync files with S3
        run: |
          aws s3 sync ./documentation/images s3://${{env.S3_BUCKET}}/images/ --delete --quiet
          echo "Files sync done!"